name: fe
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_chat_bubble: ^2.0.0
  url_launcher: ^6.0.18
  flutterfire_ui: ^0.3.0

  image_picker: ^0.8.4+6

  extended: ^0.1.5

  flutter_app_badger: ^1.3.0

  fireflutter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

