export const ERROR_TEST = "ERROR_TEST";
export const ERROR_USER_EXISTS = "ERROR_USER_EXISTS";
export const ERROR_EMPTY_UID = "ERROR_EMPTY_UID";
export const ERROR_EMPTY_ID = "ERROR_EMPTY_ID";
export const ERROR_EMPTY_CATEGORY = "ERROR_EMPTY_CATEGORY";
export const ERROR_CATEGORY_NOT_EXISTS = "ERROR_CATEGORY_NOT_EXISTS";
export const ERROR_NO_QUIZ_BY_THAT_ID = "ERROR_NO_QUIZ_BY_THAT_ID";
export const ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE = "ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE";
export const ERROR_LOGIN_FIRST = "ERROR_LOGIN_FIRST";
export const ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD";

export const ERROR_EMPTY_PASSWORD = "ERROR_EMPTY_PASSWORD";
export const ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";

export const ERROR_USER_AUTH_NOT_FOUND = "ERROR_USER_AUTH_NOT_FOUND";
export const ERROR_USER_DOC_NOT_FOUND = "ERROR_USER_DOC_NOT_FOUND";

export const ERROR_POST_NOT_EXIST = "ERROR_POST_NOT_EXIST";
export const ERROR_NOT_YOUR_POST = "ERROR_NOT_YOUR_POST";

export const ERROR_YOU_ARE_NOT_ADMIN = "ERROR_YOU_ARE_NOT_ADMIN";
// export const ERROR_CREATE_FAILED = "ERROR_CREATE_FAILED";
export const ERROR_UPDATE_FAILED = "ERROR_UPDATE_FAILED";
export const ERROR_ALREADY_DELETED = "ERROR_ALREADY_DELETED";
export const ERROR_COMMENT_NOT_EXISTS = "ERROR_COMMENT_NOT_EXISTS";
export const ERROR_NOT_YOUR_COMMENT = "ERROR_NOT_YOUR_COMMENT";

export const ERROR_EMPTY_UIDS = "ERROR_EMPTY_UIDS";
export const ERROR_EMPTY_TOPIC = "ERROR_EMPTY_TOPIC";
export const ERROR_EMPTY_TOKENS = "ERROR_EMPTY_TOKENS";
export const ERROR_TITLE_AND_BODY_CANT_BE_BOTH_EMPTY = "ERROR_TITLE_AND_BODY_CANT_BE_BOTH_EMPTY";
export const ERROR_EMTPY_EMAIL_AND_PHONE_NUMBER = "ERROR_EMTPY_EMAIL_AND_PHONE_NUMBER";
export const ERROR_ONE_OF_EMAIL_AND_PHONE_NUMBER_MUST_BY_EMPTY = "ERROR_ONE_OF_EMAIL_AND_PHONE_NUMBER_MUST_BY_EMPTY";

export const ERROR_JOB_NOT_EXIST = "ERROR_JOB_NOT_EXIST";
export const ERROR_NOT_YOUR_JOB = "ERROR_NOT_YOUR_JOB";
export const ERROR_EMPTY_COMPANY_NAME = "ERROR_EMPTY_COMPANY_NAME";
// export const ERROR_EMPTY_PROVINCE = "ERROR_EMPTY_PROVINCE";
export const ERROR_EMPTY_SINM = "ERROR_EMPTY_SINM";
export const ERROR_EMPTY_SGGNM = "ERROR_EMPTY_SGGNM";
export const ERROR_EMPTY_COMPANY_DETAIL_ADDRESS = "ERROR_EMPTY_COMPANY_DETAIL_ADDRESS";

export const ERROR_JOB_ALREADY_CREATED = "ERROR_JOB_ALREADY_CREATED";
export const ERROR_LACK_OF_POINT = "ERROR_LACK_OF_POINT";

export const ERROR_EMPTY_COMPANY_MOBILE_NUMBER = "ERROR_EMPTY_COMPANY_MOBILE_NUMBER";
export const ERROR_EMPTY_COMPANY_OFFICE_PHONE_NUMBER = "ERROR_EMPTY_COMPANY_OFFICE_PHONE_NUMBER";
export const ERROR_EMPTY_COMPANY_EMAIL_ADDRESS = "ERROR_EMPTY_COMPANY_EMAIL_ADDRESS";
export const ERROR_EMPTY_COMPANY_ABOUT_US = "ERROR_EMPTY_COMPANY_ABOUT_US";
export const ERROR_EMPTY_JOB_CATEGORY = "ERROR_EMPTY_JOB_CATEGORY";
export const ERROR_EMPTY_JOB_WORKING_DAYS = "ERROR_EMPTY_JOB_WORKING_DAYS";
export const ERROR_EMPTY_JOB_WORKING_HOURS = "ERROR_EMPTY_JOB_WORKING_HOURS";
export const ERROR_EMPTY_JOB_SALARY = "ERROR_EMPTY_JOB_SALARY";
export const ERROR_EMPTY_JOB_NUMBER_OF_HIRING = "ERROR_EMPTY_JOB_NUMBER_OF_HIRING";
export const ERROR_EMPTY_JOB_DESCRIPTION = "ERROR_EMPTY_JOB_DESCRIPTION";
export const ERROR_EMPTY_JOB_REQUIREMENT = "ERROR_EMPTY_JOB_REQUIREMENT";

export const ERROR_EMPTY_JOB_DUTY = "ERROR_EMPTY_JOB_DUTY";
export const ERROR_EMPTY_JOB_BENEFIT = "ERROR_EMPTY_JOB_BENEFIT";
export const ERROR_EMPTY_JOB_ACCOMODATION = "ERROR_EMPTY_JOB_ACCOMODATION";
