export const ERROR_USER_EXISTS = "ERROR_USER_EXISTS";
export const ERROR_EMPTY_UID = "ERROR_EMPTY_UID";
export const ERROR_EMPTY_ID = "ERROR_EMPTY_ID";
export const ERROR_EMPTY_CATEGORY = "ERROR_EMPTY_CATEGORY";
export const ERROR_CATEGORY_NOT_EXISTS = "ERROR_CATEGORY_NOT_EXISTS";
export const ERROR_NO_QUIZ_BY_THAT_ID = "ERROR_NO_QUIZ_BY_THAT_ID";
export const ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE = "ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE";
export const ERROR_LOGIN_FIRST = "ERROR_LOGIN_FIRST";
export const ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD";

export const ERROR_EMPTY_PASSWORD = "ERROR_EMPTY_PASSWORD";
export const ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";

export const ERROR_POST_NOT_EXIST = "ERROR_POST_NOT_EXIST";
export const ERROR_NOT_YOUR_POST = "ERROR_NOT_YOUR_POST";

export const ERROR_YOU_ARE_NOT_ADMIN = "ERROR_YOU_ARE_NOT_ADMIN";
// export const ERROR_CREATE_FAILED = "ERROR_CREATE_FAILED";
export const ERROR_UPDATE_FAILED = "ERROR_UPDATE_FAILED";
export const ERROR_ALREADY_DELETED = "ERROR_ALREADY_DELETED";
export const ERROR_COMMENT_NOT_EXISTS = "ERROR_COMMENT_NOT_EXISTS";
export const ERROR_NOT_YOUR_COMMENT = "ERROR_NOT_YOUR_COMMENT";

export const ERROR_EMPTY_UIDS = "ERROR_EMPTY_UIDS";
export const ERROR_EMPTY_TOPIC = "ERROR_EMPTY_TOPIC";
export const ERROR_EMPTY_TOKENS = "ERROR_EMPTY_TOKENS";
export const ERROR_TITLE_AND_BODY_CANT_BE_BOTH_EMPTY = "ERROR_TITLE_AND_BODY_CANT_BE_BOTH_EMPTY";
export const ERROR_EMTPY_EMAIL_AND_PHONE_NUMBER = "ERROR_EMTPY_EMAIL_AND_PHONE_NUMBER";
export const ERROR_ONE_OF_EMAIL_AND_PHONE_NUMBER_MUST_BY_EMPTY =
  "ERROR_ONE_OF_EMAIL_AND_PHONE_NUMBER_MUST_BY_EMPTY";

  
