export const ERROR_USER_EXISTS = "ERROR_USER_EXISTS";
export const ERROR_EMPTY_UID = "ERROR_EMPTY_UID";
export const ERROR_EMPTY_CATEGORY = "ERROR_EMPTY_CATEGORY";
export const ERROR_NO_QUIZ_BY_THAT_ID = "ERROR_NO_QUIZ_BY_THAT_ID";
export const ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE = "ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE";
export const ERROR_LOGIN_FIRST = "ERROR_LOGIN_FIRST";
export const ERROR_AUTH_FAILED = "ERROR_AUTH_FAILED";

export const ERROR_EMPTY_PASSWORD = "ERROR_EMPTY_PASSWORD";

export const ERROR_POST_NOT_EXIST = "ERROR_POST_NOT_EXIST";
