// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7F2M1mY65mRnpjM0XZIO-7QRvWIjQaqA',
    appId: '1:649893238215:web:adfddef52a8eb075cfb5e2',
    messagingSenderId: '649893238215',
    projectId: 'fireflutter-example-2',
    authDomain: 'fireflutter-example-2.firebaseapp.com',
    storageBucket: 'fireflutter-example-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRG7fCieQVqn80Lde6lixQHwqz--LHsRE',
    appId: '1:649893238215:android:bc72a3e36eaea829cfb5e2',
    messagingSenderId: '649893238215',
    projectId: 'fireflutter-example-2',
    storageBucket: 'fireflutter-example-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxbwNRfDaOWsqLb2GjquQPNm8HMWClSY8',
    appId: '1:649893238215:ios:ee35c4689f86a611cfb5e2',
    messagingSenderId: '649893238215',
    projectId: 'fireflutter-example-2',
    storageBucket: 'fireflutter-example-2.appspot.com',
    iosClientId: '649893238215-qaok8mmd7anjkitkbe21idugg61lqhjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
