"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERROR_EMPTY_PASSWORD = exports.ERROR_AUTH_FAILED = exports.ERROR_LOGIN_FIRST = exports.ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE = exports.ERROR_NO_QUIZ_BY_THAT_ID = exports.ERROR_EMPTY_CATEGORY = exports.ERROR_EMPTY_UID = exports.ERROR_USER_EXISTS = void 0;
exports.ERROR_USER_EXISTS = "ERROR_USER_EXISTS";
exports.ERROR_EMPTY_UID = "ERROR_EMPTY_UID";
exports.ERROR_EMPTY_CATEGORY = "ERROR_EMPTY_CATEGORY";
exports.ERROR_NO_QUIZ_BY_THAT_ID = "ERROR_NO_QUIZ_BY_THAT_ID";
exports.ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE = "ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE";
exports.ERROR_LOGIN_FIRST = "ERROR_LOGIN_FIRST";
exports.ERROR_AUTH_FAILED = "ERROR_AUTH_FAILED";
exports.ERROR_EMPTY_PASSWORD = "ERROR_EMPTY_PASSWORD";
//# sourceMappingURL=defines.js.map