"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERROR_UPDATE_FAILED = exports.ERROR_CREATE_FAILED = exports.ERROR_YOU_ARE_NOT_ADMIN = exports.ERROR_NOT_YOUR_POST = exports.ERROR_POST_NOT_EXIST = exports.ERROR_EMPTY_PASSWORD = exports.ERROR_WRONG_PASSWORD = exports.ERROR_LOGIN_FIRST = exports.ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE = exports.ERROR_NO_QUIZ_BY_THAT_ID = exports.ERROR_EMPTY_CATEGORY = exports.ERROR_EMPTY_ID = exports.ERROR_EMPTY_UID = exports.ERROR_USER_EXISTS = void 0;
exports.ERROR_USER_EXISTS = "ERROR_USER_EXISTS";
exports.ERROR_EMPTY_UID = "ERROR_EMPTY_UID";
exports.ERROR_EMPTY_ID = "ERROR_EMPTY_ID";
exports.ERROR_EMPTY_CATEGORY = "ERROR_EMPTY_CATEGORY";
exports.ERROR_NO_QUIZ_BY_THAT_ID = "ERROR_NO_QUIZ_BY_THAT_ID";
exports.ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE = "ERROR_CANNOT_ANSWER_SAME_QUESTION_TWICE";
exports.ERROR_LOGIN_FIRST = "ERROR_LOGIN_FIRST";
exports.ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD";
exports.ERROR_EMPTY_PASSWORD = "ERROR_EMPTY_PASSWORD";
exports.ERROR_POST_NOT_EXIST = "ERROR_POST_NOT_EXIST";
exports.ERROR_NOT_YOUR_POST = "ERROR_NOT_YOUR_POST";
exports.ERROR_YOU_ARE_NOT_ADMIN = "ERROR_YOU_ARE_NOT_ADMIN";
exports.ERROR_CREATE_FAILED = "ERROR_CREATE_FAILED";
exports.ERROR_UPDATE_FAILED = "ERROR_UPDATE_FAILED";
//# sourceMappingURL=defines.js.map